name: maven-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y update
        sudo apt-get -y install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Maven Dependencies Cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-mvn-cache-${{ hashFiles('**/pom.xml') }}
    - name: Maven Test
      run: |
        mvn -B test --file pom.xml